### ISSUE TITLE
დამატებიტი ასოები bluetooth კლავიატურაზე

### ISSUE THREAD

**Issue by AlexCzar** [Stichoza/AnySoftKeyboardLanguagePackGeorgian#1]
გაუმარჯოს. ყველაზე გამოსადეგი layout-ია, მაგრამ bluetooth კლავიატურის სეერტებისას ვერ ვიყენებ ისეტ ასოებს, რომლებიც აკლია ამ ტექსტსი, რაც ნატლად ცანს :)
როგორმე რომ დაამატო ეს სესაზლებლობა (მაგალიტად, როგორც არის PCზე - ყველაზე კარგი ვარიანტი).

**Comment by Stichoza** [comment]
სალამი და მადლობა Issue-ს გახსნისთვის :) ბლუთუს კლავიატურა, როგორც ვხვდები ჩვეულებრივი Qwerty წყობისაა ხომ? ზუსტად არ ვიცი რა პრინციპით დამატებული იმუშავებს ბლუთუსზე (double click თუ press and hold, თუ უბრალოდ shift) და გავარკვევ ამას...

სხვა დანარჩენი ღილაკები წესიერად მუშაობს ლათინური ღილაკების შესაბამისად? რამე აცდენა ხომ არაა?

**Comment by AlexCzar** [comment]
სხვა ყველაფერი მუშაობს 5ზე :) მადლობა. ისე ჯობია shift-ით რა თქმა უნდა.

**Comment by Stichoza** [comment]
კი, Shift-ით ჯობია. მეც ეგრე ვთვლი, მაგრამ მგონი ეგ პრობლემა იქნება, რადგან თვითონ [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) არ მომცემს მაგის საშუალებას. როგორც ჯერჯერობით გავარკვიე, shift-ს შესაბამისი ასო უბრალოდ Uppercase-ში გადაჰყავს, ქართულში კი აფერქეისი არაა, ანუ არც `თ` არაა `ტ`-ს აფერქეის ვერსია.

ამასაც გავარკვევ, იქნებ გამოვიდეს და ალბათ უახლოეს მომავალში ფიზიკურ კლავიატურასაც ვიშოვი, რომ დავტესტო :yum:

**Comment by AlexCzar** [comment]
double-tap მუშაობს უეჭველი, ერთ-ერთ რუსულ კლავიატურაზე, მაგალითად, სწრაფად "дд" თუ დავბეჭდავ, "э"-ს მიწერს (რაც იდიოტობაა hardware-ულ კლავიატურაზე, მაგრამ რას იზამ, არც თუ ისე ბევრ სიტყვაში არის ორმაგი д :D).

**Comment by Stichoza** [comment]
კი double მოქმედებს, keySequence-ით გაიწერება, მაგრამ ეგ მოუხერხებელია. შიფტი თუ არ გამოვა press and hold-ით რომ სხვა სიმბოლოები ამოდის, იმით გავაკეთებ. თან კლავიატურის ზედა ხაზზე იგივე press and hold-ზე რიცხვებს დავამატებ, როგორც ინგლისურ ვარიანტზეა :)

ლეპტოპი აღვადგინე მკვდრეთით და მივხედავ :> ფიზიკურ კლავიატურას ემულატორიდან გავტესტავ წესით არ უნდა იყოს პრობელმა.

**Comment by AlexCzar** [comment]
თუ გინდა, apk მომეცი, რომ გააკეთებ, და გავტესტავ, სანამ გაუშვებ play-store-ში.

**Comment by Stichoza** [comment]
`shiftModifier`-ს მივაკვლიე და ვნახოთ რა იქნება. ემულატორზე ვერ ვტესტავ და თუ არ დაგეზარება აგერ [APK ფაილი](https://dl.dropbox.com/u/37459602/AnySoft_test/ask_phys_keymap.apk) და ნახე რას იზამს. სატესტოდ ასე გავაკეთე:
- ორმაგი `წ,წ` - **ჭ**
- `Shift+R` - **ღ** (Unicode სიმბოლოთი)
- `Shift+T` - **თ** (კოდით)

რომელი როგორ იმუშავებს მითხარი და იმის მიხედვით გავაგრძელებ :) _PS._ ზემოთა რიგზე press and hold-ზე რიცხვები დავამატე **არა**ფიზიკური კლავიატურისთვის

**Comment by AlexCzar** [comment]
დღეს საღამოს გავტესტავ აუცილებლად და შეგატყობინებ!

**Comment by AlexCzar** [comment]
სამწუხაროდ არც ერთმა ვერსიამ ვერ იმუშავა, თუმცა ლადო კუმსიაშვილის layoutზე double click მუშაობს. მაგისი პაკეტის სორსი უცბად ვერ მოვძებნე სმარტფონიდან, დილით კიდევ ვცდი და ვნახოთ, ის როგორ ახერხებს მაგას.
რაც შეეხება ზემოთა რიგს, ციფრები დაემატა მართლაც და ქწერ ასოებს კიდევ დაემატა qwer ასოები რატომღაც.

**Comment by Stichoza** [comment]
კი, qwer მე მივამატე და დამავიწყდა წაშლა. ეს ვერსია გავაკეთე Hebrew კლავიატურის მიხედვით და როგორც აღმოჩნდა, ძველი სორსი ყოფილა. ახლა [keycode](https://github.com/Stichoza/AnySoftKeyboardLanguagePackGeorgian/blob/master/res/xml/physical.xml#L11-L17)-ებზე გადავწერე და თუ ძალიან არ შეგაწუხე, [ეს ვერსია](https://dl.dropbox.com/u/37459602/AnySoft_test/ask_phys_keymap_v2.apk) დატესტე, როცა შეძლებ.

Shift-ზე უნდა იმუშაოს წესით w, r, t, s, j, z, c ღილაკებმა...

**Comment by AlexCzar** [comment]
ეს შეტყობინება დავწერე bluetooth კლავიატურის მეშვეობით. ყველა ღილაკი შევამოწმე.
მუშაობს ხუთიანზე :+1:

**Comment by Stichoza** [comment]
ძალიან ძალიან დიდი მადლობა :+1: დღეს თუ არა, ხვალ ავტვირთავ მარკეტზე ახალ ვერსიას :) გარდა ამისა, დავამატე ძველქართული ასოებიც `ჱ` `ჲ` `ჳ` და ა.შ. ვირტუალურზე popup-ებზე და ფიზიკურზე shift-ით Y-P ღილაკებზე.

რახან პრობლემა ამოიწურა, Issue-ს დახურულად მოვნიშნავ. კიდევ ერთხელ მადლობა.
